version: "3"

networks:
  subsquid-mappings-khala_web_network:
    external: true
    driver: bridge
  db_network:
    driver: bridge

services:
  query-node:
    build:
      context: .
      target: query-node
    ports:
      - 4000
    environment:
      DB_HOST: db
    restart: unless-stopped
    networks:
      - subsquid-mappings-khala_web_network
      - db_network

  processor:
     build:
       context: .
       target: processor
     environment:
       DB_HOST: db
     ports:
       - 3000
     restart: unless-stopped
     networks:
       - db_network

  migrate:
    build:
      context: .
      target: migrate
    environment:
      DB_HOST: db
    depends_on:
      - db
    networks:
      - db_network

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432
    networks:
      - db_network