version: '3'

networks:
  web_network:
    external: true
    driver: bridge
  db_network:
    driver: bridge

services:
  query-node:
    profiles:
      - querying
    build:
      context: .
      target: queryNode
    ports:
      - 4001
    environment:
      DB_HOST: db
      GQL_PORT: 4001
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - web_network
      - db_network

  processor:
    profiles:
      - indexing
    build:
      context: .
      target: processor
    environment:
      DB_HOST: db
    ports:
      - 3000
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - db_network

  migrate:
    build:
      context: .
      target: migrate
    environment:
      DB_HOST: db
    depends_on:
      - db
    networks:
      - db_network

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../../data/db/${COMPOSE_PROJECT_NAME}/:/var/lib/postgresql/data
    ports:
      - 5432
    networks:
      - db_network
