name: Deploy
on:
    workflow_dispatch:
      inputs:
        prawn:
          description: "Prawn to deploy"
          required: true
        branch:
          description: "Branch or commit hash to deploy"
          default: "main"
          required: true


jobs:
  snapshot:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SNAPSHOT_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SNAPSHOT_KNOWN_HOSTS }}
      - name: Snapshot
        run: ssh github-actions@${{ secrets.SNAPSHOT_HOST }} "cd /srv/squid && git fetch && git checkout ${{ github.event.inputs.branch }} && git pull && yarn devkit snapshot make ${{ github.event.inputs.prawn }}"

  deploy:
    needs: snapshot
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Deploy
        run: ssh github-actions@${{ secrets.HOST }} "cd /srv/www/squid && git fetch && git checkout ${{ github.event.inputs.branch }} &&  git pull && yarn devkit snapshot restore ${{ github.event.inputs.prawn }} && yarn devkit deploy ${{ github.event.inputs.prawn }}"
